export const HOME_ROUTE: string = "/"
export const PROJECTS_ROUTE: string = "/projects"
export const EXPERIENCES_ROUTE: string = "/experiences"
export const OTHERS_ROUTE: string = "/others"
export const VIEW_ROUTE: string = "/view"